Repository openshift/azure-disk-csi-driver-operator, pull requests merged in 2021-04, with the labels that each got.

#7 Include CSIDriver creation in Operator
  assets/csidriver.yaml
  pkg/generated/bindata.go
  pkg/operator/starter.go
Labels: approved, lgtm

#8 Add CSI certification test manifest
  test/e2e/manifest.yaml
Labels: approved, lgtm

#10 Add "managed" annotation to CSIDriver
  assets/csidriver.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm

#11 Bug 1947767: Updates default SC to Premium SKU
  assets/storageclass.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#12 Bug 1947756: Add maxUnavailable to DaemonSet
  assets/node.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#13 Bug 1948555: Set timeouts according to upstream
  assets/controller.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#14 Bug 1948603: Fix some failing tests
  assets/controller.yaml
  assets/rbac/resizer_role.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#15 Bug 1948603: Disable volume expansion e2e tests
  test/e2e/manifest.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#16 Bug 1947774: fix imagePullPolicy to ifNotPresent
  assets/controller.yaml
  assets/node.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
