Repository openshift/azure-disk-csi-driver-operator, pull requests merged in 2023-02, with the labels that each got.

#63 STOR-947: support disabling default StorageClass via ClusterCSIDriver
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csicontrollerset/csi_controller_set.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/modules.txt
Labels: lgtm, approved, docs-approved, px-approved, qe-approved

#67 OCPBUGS-6658: Disable managed identity authentication
  assets/controller.yaml
  assets/node.yaml
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#69 OCPBUGS-7617: Adjust client-side QPS, burst and worker threads in provisioner and attacher sidecars
  assets/controller.yaml
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference
