Repository openshift/azure-disk-csi-driver-operator, pull requests merged in 2023-07, with the labels that each got.

#84 STOR-1065: Rework sidecar bindings to bind common ClusterRoles
  assets/rbac/attacher_role.yaml
  assets/rbac/lease_leader_election_role.yaml
  assets/rbac/lease_leader_election_rolebinding.yaml
  assets/rbac/main_attacher_binding.yaml
  assets/rbac/main_provisioner_binding.yaml
  assets/rbac/main_resizer_binding.yaml
  assets/rbac/main_snapshotter_binding.yaml
  assets/rbac/provisioner_role.yaml
  assets/rbac/resizer_role.yaml
  assets/rbac/snapshotter_role.yaml
  assets/rbac/storageclass_reader_resizer_binding.yaml
  pkg/operator/starter.go
Labels: lgtm, approved, docs-approved, px-approved, qe-approved, jira/valid-reference

#89 OCPBUGS-16783: Chore: Update OWNERS
  OWNERS
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#90 OCPBUGS-16496: Bump library-go to remove dependency on goproxy
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csicontrollerset/csi_controller_set.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
  vendor/k8s.io/apimachinery/pkg/util/wait/loop.go
  vendor/k8s.io/apiserver/pkg/cel/common/values.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/server/storage/storage_factory.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/healthcheck.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/openapi/client.go
  vendor/k8s.io/client-go/openapi/groupversion.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/kube-openapi/pkg/handler/handler.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/metrics/metrics.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/types.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/clientset.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/migration_client.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#88 OCPBUGS-16654: Revert revert "STOR-1065: Rework sidecar bindings to b…
  assets/rbac/attacher_role.yaml
  assets/rbac/lease_leader_election_role.yaml
  assets/rbac/lease_leader_election_rolebinding.yaml
  assets/rbac/main_attacher_binding.yaml
  assets/rbac/main_provisioner_binding.yaml
  assets/rbac/main_resizer_binding.yaml
  assets/rbac/main_snapshotter_binding.yaml
  assets/rbac/provisioner_role.yaml
  assets/rbac/resizer_role.yaml
  assets/rbac/snapshotter_role.yaml
  assets/rbac/storageclass_reader_resizer_binding.yaml
  pkg/operator/starter.go
Labels: lgtm, approved, docs-approved, px-approved, jira/valid-bug, jira/valid-reference
